apiVersion: v1
kind: Service
metadata:
  name: service
  labels:
    run: survey
spec:
  type: NodePort
  selector:
    app: survey
  ports:
  - port: 8080
    targetPort: 8080
    protocol: TCP
    nodePort: 30000
