# GroupName: TeamPRTV (Preethi Ranganathan, Mary Rithika Reddy Gade, Tarun Vinay Gujjar, Vikas Halgar Seetharam)
# This is the service yaml file

apiVersion: v1
kind: Service
metadata:
  name: service
  labels:
    run: survey
spec:
  type: LoadBalancer
  selector:
    app: survey
  ports:
  - port: 8080
    targetPort: 8080
    protocol: TCP