# GroupName: TeamPRTV (Preethi Ranganathan, Mary Rithika Reddy Gade, Tarun Vinay Gujjar, Vikas Halgar Seetharam)
# This is the cluster yaml file

apiVersion: provisioning.cattle.io/v1
kind: Cluster
metadata:
  annotations:
    field.cattle.io/creatorId: user-76zdb
  creationTimestamp: '2024-03-18T16:57:01Z'
  finalizers:
    - wrangler.cattle.io/cloud-config-secret-remover
    - wrangler.cattle.io/provisioning-cluster-remove
    - wrangler.cattle.io/rke-cluster-remove
  generation: 2
  managedFields:
    - apiVersion: provisioning.cattle.io/v1
      fieldsType: FieldsV1
      fieldsV1:
        f:metadata:
          f:finalizers:
            v:"wrangler.cattle.io/provisioning-cluster-remove": {}
            v:"wrangler.cattle.io/rke-cluster-remove": {}
        f:spec:
          .: {}
          f:kubernetesVersion: {}
          f:localClusterAuthEndpoint: {}
          f:rkeConfig:
            .: {}
            f:chartValues:
              .: {}
              f:rke2-calico: {}
            f:etcd:
              .: {}
              f:snapshotRetention: {}
              f:snapshotScheduleCron: {}
            f:machineGlobalConfig:
              .: {}
              f:cni: {}
              f:disable-kube-proxy: {}
              f:etcd-expose-metrics: {}
            f:machineSelectorConfig: {}
            f:registries: {}
            f:upgradeStrategy:
              .: {}
              f:controlPlaneConcurrency: {}
              f:controlPlaneDrainOptions:
                .: {}
                f:deleteEmptyDirData: {}
                f:disableEviction: {}
                f:enabled: {}
                f:force: {}
                f:gracePeriod: {}
                f:ignoreDaemonSets: {}
                f:skipWaitForDeleteTimeoutSeconds: {}
                f:timeout: {}
              f:workerConcurrency: {}
              f:workerDrainOptions:
                .: {}
                f:deleteEmptyDirData: {}
                f:disableEviction: {}
                f:enabled: {}
                f:force: {}
                f:gracePeriod: {}
                f:ignoreDaemonSets: {}
                f:skipWaitForDeleteTimeoutSeconds: {}
                f:timeout: {}
      manager: rancher
      operation: Update
      time: '2024-03-18T16:57:01Z'
    - apiVersion: provisioning.cattle.io/v1
      fieldsType: FieldsV1
      fieldsV1:
        f:metadata:
          f:finalizers:
            .: {}
            v:"wrangler.cattle.io/cloud-config-secret-remover": {}
        f:spec:
          f:rkeConfig:
            f:machinePoolDefaults: {}
            f:upgradeStrategy:
              f:controlPlaneDrainOptions:
                f:ignoreErrors: {}
                f:postDrainHooks: {}
                f:preDrainHooks: {}
              f:workerDrainOptions:
                f:ignoreErrors: {}
                f:postDrainHooks: {}
                f:preDrainHooks: {}
      manager: rancher-v2.8.2-secret-migrator
      operation: Update
      time: '2024-03-18T16:57:01Z'
    - apiVersion: provisioning.cattle.io/v1
      fieldsType: FieldsV1
      fieldsV1:
        f:status:
          .: {}
          f:agentDeployed: {}
          f:clientSecretName: {}
          f:clusterName: {}
          f:conditions: {}
          f:fleetWorkspaceName: {}
          f:observedGeneration: {}
          f:ready: {}
      manager: rancher
      operation: Update
      subresource: status
      time: '2024-03-18T20:17:40Z'
  name: swe645-hw2-cluster
  namespace: fleet-default
  resourceVersion: '105022'
  uid: e9e1417a-30b6-4476-80a1-7e16f879e0fd
spec:
  kubernetesVersion: v1.27.11+rke2r1
  localClusterAuthEndpoint: {}
  rkeConfig:
    chartValues:
      rke2-calico: {}
    etcd:
      snapshotRetention: 5
      snapshotScheduleCron: 0 */5 * * *
    machineGlobalConfig:
      cni: calico
      disable-kube-proxy: false
      etcd-expose-metrics: false
    machinePoolDefaults: {}
    machineSelectorConfig:
      - config:
          protect-kernel-defaults: false
    registries: {}
    upgradeStrategy:
      controlPlaneConcurrency: '1'
      controlPlaneDrainOptions:
        deleteEmptyDirData: true
        disableEviction: false
        enabled: false
        force: false
        gracePeriod: -1
        ignoreDaemonSets: true
        ignoreErrors: false
        postDrainHooks: null
        preDrainHooks: null
        skipWaitForDeleteTimeoutSeconds: 0
        timeout: 120
      workerConcurrency: '1'
      workerDrainOptions:
        deleteEmptyDirData: true
        disableEviction: false
        enabled: false
        force: false
        gracePeriod: -1
        ignoreDaemonSets: true
        ignoreErrors: false
        postDrainHooks: null
        preDrainHooks: null
        skipWaitForDeleteTimeoutSeconds: 0
        timeout: 120
status:
  agentDeployed: true
  clientSecretName: swe645-hw2-cluster-kubeconfig
  clusterName: c-m-gl2rf996
  conditions:
    - lastUpdateTime: '2024-03-18T17:31:50Z'
      status: 'False'
      type: Reconciling
    - lastUpdateTime: '2024-03-18T16:57:01Z'
      status: 'False'
      type: Stalled
    - lastUpdateTime: '2024-03-18T20:17:35Z'
      status: 'True'
      type: Created
    - lastUpdateTime: '2024-03-18T20:17:40Z'
      status: 'True'
      type: RKECluster
    - lastUpdateTime: '2024-03-18T16:57:01Z'
      status: 'True'
      type: BackingNamespaceCreated
    - lastUpdateTime: '2024-03-18T16:57:01Z'
      status: 'True'
      type: DefaultProjectCreated
    - lastUpdateTime: '2024-03-18T16:57:01Z'
      status: 'True'
      type: SystemProjectCreated
    - lastUpdateTime: '2024-03-18T16:57:01Z'
      status: 'True'
      type: InitialRolesPopulated
    - lastUpdateTime: '2024-03-18T20:17:35Z'
      status: 'True'
      type: Updated
    - lastUpdateTime: '2024-03-18T20:17:35Z'
      status: 'True'
      type: Provisioned
    - lastUpdateTime: '2024-03-18T20:17:40Z'
      status: 'True'
      type: Ready
    - lastUpdateTime: '2024-03-18T16:57:03Z'
      status: 'True'
      type: CreatorMadeOwner
    - lastUpdateTime: '2024-03-18T16:57:04Z'
      status: 'True'
      type: NoDiskPressure
    - lastUpdateTime: '2024-03-18T16:57:04Z'
      status: 'True'
      type: NoMemoryPressure
    - lastUpdateTime: '2024-03-18T16:57:04Z'
      status: 'True'
      type: SecretsMigrated
    - lastUpdateTime: '2024-03-18T16:57:04Z'
      status: 'True'
      type: ServiceAccountSecretsMigrated
    - lastUpdateTime: '2024-03-18T16:57:04Z'
      status: 'True'
      type: RKESecretsMigrated
    - lastUpdateTime: '2024-03-18T16:57:04Z'
      status: 'True'
      type: ACISecretsMigrated
    - lastUpdateTime: '2024-03-18T20:17:35Z'
      status: 'True'
      type: Connected
    - lastUpdateTime: '2024-03-18T17:31:21Z'
      status: 'True'
      type: GlobalAdminsSynced
    - lastUpdateTime: '2024-03-18T17:31:22Z'
      status: 'True'
      type: SystemAccountCreated
    - lastUpdateTime: '2024-03-18T17:31:25Z'
      status: 'True'
      type: AgentDeployed
    - lastUpdateTime: '2024-03-18T17:31:50Z'
      status: 'True'
      type: Waiting
  fleetWorkspaceName: fleet-default
  observedGeneration: 2
  ready: true
